export default {
  login: "ginwan",
  id: 50168816,
  node_id: "MDQ6VXNlcjUwMTY4ODE2",
  avatar_url: "https://avatars.githubusercontent.com/u/50168816?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ginwan",
  html_url: "https://github.com/ginwan",
  followers_url: "https://api.github.com/users/ginwan/followers",
  following_url: "https://api.github.com/users/ginwan/following{/other_user}",
  gists_url: "https://api.github.com/users/ginwan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ginwan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ginwan/subscriptions",
  organizations_url: "https://api.github.com/users/ginwan/orgs",
  repos_url: "https://api.github.com/users/ginwan/repos",
  events_url: "https://api.github.com/users/ginwan/events{/privacy}",
  received_events_url: "https://api.github.com/users/ginwan/received_events",
  type: "User",
  site_admin: false,
  name: "Ginwan",
  company: "...",
  blog: "",
  location: "Khartoum",
  email: null,
  hireable: null,
  bio: "I am a software developer interested in web development.",
  twitter_username: null,
  public_repos: 5,
  public_gists: 16,
  followers: 0,
  following: 1,
  created_at: "2019-05-01T10:23:14Z",
  updated_at: "2022-07-18T15:30:02Z",
};
